name: binder_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - notebook>5.2
  - jupyterlab>1.1
  - ipywidgets
  - scipy
  - vtk
  - pip:
     - k3d
     - nibabel
     - vedo