#!/bin/bash
cd /tmp
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter nbextension enable k3d --py --sys-prefix
jupyter labextension install k3d
jupyter nbextension install --py --sys-prefix k3d
